-- MySQL Script generated by MySQL Workbench
-- Sun Jan 16 17:36:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stations` (
  `StatonID` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `geo_point` VARCHAR(45) NULL,
  PRIMARY KEY (`StatonID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`observation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`observation` (
  `reading_id` INT NOT NULL,
  `Datetime` VARCHAR(45) NULL,
  `Site ID` VARCHAR(45) NULL,
  `NOx` INT NULL,
  `NO2` INT NULL,
  `NO` INT NULL,
  `PM10` INT NULL,
  `NVPM10` INT NULL,
  `VPM10` INT NULL,
  `NVOM2.5` INT NULL,
  `PM2.5` INT NULL,
  `VPM2.5` INT NULL,
  `CO` INT NULL,
  `O3` INT NULL,
  `SO2` INT NULL,
  `Temperature` INT NULL,
  `RH` INT NULL,
  `Air Pressure` INT NULL,
  `DateStart` INT NULL,
  `DateEnd` INT NULL,
  `Current` INT NULL,
  `Instrument` VARCHAR(45) NULL,
  `Stations_StatonID` INT NOT NULL,
  PRIMARY KEY (`reading_id`),
  INDEX `fk_observation_Stations_idx` (`Stations_StatonID` ASC) VISIBLE,
  CONSTRAINT `fk_observation_Stations`
    FOREIGN KEY (`Stations_StatonID`)
    REFERENCES `mydb`.`Stations` (`StatonID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schema` (
  `schemaID` INT NOT NULL,
  `meansue` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `unit` VARCHAR(45) NULL,
  `schemacol` VARCHAR(45) NULL,
  PRIMARY KEY (`schemaID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
